### ISSUE TITLE
item tag information

### ISSUE THREAD

**Issue by PlkMarudny** [inlife/aftereffects-project-research#1]
`<item>` tag - looks like 4 bytes starting from the byte 18 describe the id of an item in the ("bdata" attribute of the <idta> tag)

**Comment by PlkMarudny** [comment]
I was wrong, made more research based on some real-life project, and everything looks more complicated:

`<idta bdata="00040000000000000000000000000000af495f8300000020000000000000000000 ...`
`<ldta bdata="d7a4ac8500020000000000010002f800000064000000000000006400000fa0000000640000010007af495f8300000000000000000000 ...`

The id value is **af495f83** here, I mean it starts at 16th byte, and the id is 4 byte long.

**Comment by inlife** [comment]
that is an interesting observation, thank you
please feel free to create a pull request!

**Comment by PlkMarudny** [comment]
id in general should have a bigger capacity in theory, as you can create a project with thousands of items inside
